name: deploy vercel
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-static:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare
        run: node .preview/prepare.js
      - uses: amondnet/vercel-action@v19
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./preview
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
